language: groovy

install:
  - chmod +x shscripts/*
  - shscripts/env.sh

after_success:
  - gradle artifactoryPublish
  - gradle bintrayUpload
  - gradle publishPlugins
 
branches:
  only:
    - master
